### ISSUE TITLE
No WinTable, WinRow, WinCell functionality.

### ISSUE THREAD

**Issue by TsvetomirSlavovPortfolio** [DavidWDev/DW.CodedUI#2]
How can I get the functionality for Table, Row and Cell. I am also not able to get the Value of a Cell which is what I need to verify.

**Comment by DavidWDev** [comment]
I will have a look at it, thanks for mentioning.

**Comment by DavidWDev** [comment]
Can you tell me what kind of Table, Row and Cell you speak about?
The Table in a FlowDocument in WPF?

**Comment by DavidWDev** [comment]
Not yet.

I try to find a solution for the WPF table currently. I will need to check if this is working for WinForms too. (So far it did, good chance).
When there is a quick workaround you can use directly, I let you know.

**Comment by TsvetomirSlavovPortfolio** [comment]
Thanks David, I will follow for the updates.

**Comment by DavidWDev** [comment]
OK, thank you.
I will create a BasicDataGrid with it rows and cells and so on.

Currently, as you can see on the screenshot, you can work with the basic operations from the UI class.
the Children of the dataGridView1 are the rows, and the children for each row are the cells.

What actually is not that easy is reading of its value. But I see the cells them self supports the ValuePatternIdentifiers.

Do you need a quick solution, or can you wait till I have added the BasicDataGrid?

![image](https://user-images.githubusercontent.com/343639/39636326-28f0b5b4-4fc0-11e8-9304-6c0b4cdb2859.png)

**Comment by TsvetomirSlavovPortfolio** [comment]
I found the solution but it would be amazing if you add it to the framework.
Here it is:

public static class GetValueExtension
    {
        public static string GetText(this AutomationElement element)
        {
            object patternObj;
            if (element.TryGetCurrentPattern(ValuePattern.Pattern, out patternObj))
            {
                var valuePattern = (ValuePattern)patternObj;
                return valuePattern.Current.Value;
            }
            else if (element.TryGetCurrentPattern(TextPattern.Pattern, out patternObj))
            {
                var textPattern = (TextPattern)patternObj;
                return textPattern.DocumentRange.GetText(-1).TrimEnd('\r'); // often there is an extra '\r' hanging off the end.
            }
            else
            {
                return element.Current.Name;
            }
        }
    }

**Comment by DavidWDev** [comment]
That was the plan I was follow :-)
So you actually don't need any code that your work is blocked right now?

**Comment by TsvetomirSlavovPortfolio** [comment]
I don't need the code right now, I am using this extension to resolve GetValue(). When you implement it, I will update the NuGet, refactor and make my code cleaner. Thanks for your work! Here is some example of the controls that CUITe has implemented https://github.com/icnocop/cuite/tree/master/src/CUITe/Controls/WinControls.

**Comment by DavidWDev** [comment]
Thank you. I will add the right controls behaviors and properties to work properly with a DataGrid.
Other implementations does not make many sense to watch at, in the most cases, because my library is implemented like, that it works in every visual studio version, nor enterprise only.
But thanks anyway :-)

**Comment by TsvetomirSlavovPortfolio** [comment]
Could you also add in the next NuGet release more properties to locate the controls in the "Use" and "By" classes?

**Comment by DavidWDev** [comment]
Can you please create a new issue with it?
I would like to know what is missing, maybe there is already a solution for 😊

**Comment by TsvetomirSlavovPortfolio** [comment]
Thanks for the implementation David! Will you be creating a new NuGet version with these updates?

**Comment by DavidWDev** [comment]
Yes. A version follows this weekend. I chose this issue when it's done

**Comment by DavidWDev** [comment]
The Version 2.8.4 just got released. For a download on my website including its documentation, and on NuGet.org.
When Visual Studio is not showing the update, please wait till their cache got updated or force it to the latest 2.8.4 using the command line.

NuGet: https://www.nuget.org/packages/DW.CodedUI/
Documentation: http://libs.my-libraries.com/DW.CodedUI/v2.8.4/Documentation/index.html
Manual download and other links: http://my-libraries.com/index.php/2-uncategorised/26-dw-codedui-downloads
